### PR TITLE
Feature | Add support for Laravel 10

### PR DESCRIPTION
**Pull request by andershagbard**
I am not sure if there needs to be more done

### CODE REVIEW

**Comment by Sammyjo20** [comment]
Thank you for this @andershagbard

**Review by Sammyjo20 — APPROVED** [review]

**Comment by peterkeri** [comment]
Dear Sammy,

could you give some info about when'll you merge this? 

Thanks a lot!:)

**Comment by stephanesoares** [comment]
Hello,
I'm waiting this PR, its gonna be aproveed? 


thanks

**Comment by Sammyjo20** [comment]
Hey @stephanesoares not too much longer now! Just looking into this today.

**Comment by Sammyjo20** [comment]
All released @stephanesoares @peterkeri @andershagbard! Thank you for your help on this 

https://github.com/Sammyjo20/laravel-haystack/releases/tag/v0.11.0

**Comment by peterkeri** [comment]
> All released @stephanesoares @peterkeri @andershagbard! Thank you for your help on this 
> 
> https://github.com/Sammyjo20/laravel-haystack/releases/tag/v0.11.0

Thanks a lot!

**Pull request merged**
