### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/Sammyjo20/laravel-haystack/pull/87/commits/90a6f6453807dc2ec17cd912219508c61037212e?w=1) for Laravel 11. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-haystack.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "sammyjo20/laravel-haystack": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by nick-potts** [comment]
Any chance of getting L11 support?

**Comment by simaodiascosta** [comment]
@Sammyjo20 any chance of getting this done?

**Comment by ahmedgadit** [comment]
Hey, @Sammyjo20 waiting for the approval of this PR, Thanks for doing an awesome job sorry for popping up your notification

**Comment by use-the-fork** [comment]
For anyone needing this to be bumped to 11.x I have forked and made the update here:
https://github.com/use-the-fork/laravel-haystack

You can use `composer require use-the-fork/laravel-haystack` to use that version.

**Comment by Sammyjo20** [comment]
Hey all, sorry for the delay. I will be creating an official update soon!

**Comment by Sammyjo20** [comment]
Closing this as I am working on this on #89 🙌

**Pull request closed without merging**
